# SQL Manager 2011 Lite for MySQL 5.0.0.3
# ---------------------------------------
# Host     : localhost
# Port     : 3306
# Database : td_remote


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES cp1251 */;

SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE `td_remote`
    CHARACTER SET 'cp1251'
    COLLATE 'cp1251_general_ci';

USE `td_remote`;

#
# Structure for the `td_messages` table : 
#

CREATE TABLE `td_messages` (
  `MSG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPERATION_NAME` varchar(50) NOT NULL DEFAULT 'no_action',
  `OPERATION_ID` int(11) NOT NULL DEFAULT '0',
  `SOURCE_ID` int(11) NOT NULL DEFAULT '0',
  `DEST_ID` int(11) NOT NULL DEFAULT '0',
  `OBJ_ID` int(11) NOT NULL DEFAULT '0',
  `STR_PARAM_1` varchar(255) DEFAULT 'Пустое сообщение',
  `STR_PARAM_2` varchar(255) DEFAULT NULL,
  `STR_PARAM_3` varchar(255) DEFAULT NULL,
  `INT_PARAM_1` int(11) DEFAULT NULL,
  `INT_PARAM_2` int(11) DEFAULT NULL,
  `INT_PARAM_3` int(11) DEFAULT NULL,
  `IN_DEST` int(11) NOT NULL DEFAULT '0',
  `ANSWER` int(11) NOT NULL DEFAULT '0',
  `CREATE_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MSG_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=cp1251;



/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;